FROM python:3.8
ARG DEBIAN_FRONTEND=noninteractive

COPY requirements_repro.txt ./requirements_repro.txt

RUN python -m pip install -U pip && \
    python -m pip install -r requirements_repro.txt && \
    python -m pip cache purge

RUN python -m nltk.downloader stopwords

WORKDIR /app/

CMD dvc pull && dvc repro && cat metrics.json
