FROM python:3.8
ARG DEBIAN_FRONTEND=noninteractive

COPY requirements.txt ./requirements.txt

RUN python -m pip install -U pip && \
    python -m pip install -r requirements.txt && \
    python -m pip cache purge

RUN python -m nltk.downloader stopwords

COPY ./resources/model.pkl /app/resources/model.pkl
COPY ./src/ /app/src/

WORKDIR /app/

CMD uvicorn src.start_api:app --host=0.0.0.0 --port=${PORT:-5011}